[[redirects]]
  from = "/index.html"
  to = "/obsidian\export_HTML/개발-및-공부-히스토리.html"
  status = 200
  force=true

[[redirects]]
  from = "/"
  to = "/obsidian\export_HTML/개발-및-공부-히스토리.html"
  status = 200
  force=true